### ISSUE TITLE
Error importing epub

### ISSUE THREAD

**Issue by SteveRidout** [Vaporbook/epub-parser#2]
I've encountered an error while parsing, here's the console output including a stack trace:

opsRoot is: (derived from content.opf)
parsing OPF data

events.js:72
        throw er; // Unhandled 'error' event
              ^
TypeError: Cannot read property 'length' of undefined
    at /Users/steveridout/code/readlang/node_modules/epub-parser/lib/epub-parser.js:234:36
    at Parser.<anonymous> (/Users/steveridout/code/readlang/node_modules/epub-parser/node_modules/xml2js/lib/xml2js.js:384:20)
    at Parser.emit (events.js:95:17)
    at Object.onclosetag (/Users/steveridout/code/readlang/node_modules/epub-parser/node_modules/xml2js/lib/xml2js.js:348:26)
    at emit (/Users/steveridout/code/readlang/node_modules/epub-parser/node_modules/xml2js/node_modules/sax/lib/sax.js:615:33)
    at emitNode (/Users/steveridout/code/readlang/node_modules/epub-parser/node_modules/xml2js/node_modules/sax/lib/sax.js:620:3)
    at closeTag (/Users/steveridout/code/readlang/node_modules/epub-parser/node_modules/xml2js/node_modules/sax/lib/sax.js:861:5)
    at Object.write (/Users/steveridout/code/readlang/node_modules/epub-parser/node_modules/xml2js/node_modules/sax/lib/sax.js:1294:29)
    at Parser.exports.Parser.Parser.parseString (/Users/steveridout/code/readlang/node_modules/epub-parser/node_modules/xml2js/lib/xml2js.js:403:31)
    at Parser.parseString (/Users/steveridout/code/readlang/node_modules/epub-parser/node_modules/xml2js/lib/xml2js.js:6:61)

If you want I can privately share the offending .epub file to help reproduce the issue, I don't want to share it publicly since I don't own the copyright.

PS: thanks very much for this module!

**Comment by Vaporbook** [comment]
Hey thanks for the report. Sounds like an unexpectedly undefined 
property. Is your file epub2 or epub3? You can either send the whole 
file, or just the .opf file from inside the zip, if you know how to 
extract it. Either one might help, but the whole file would make it easier.

Aaron

**Comment by SteveRidout** [comment]
Thanks for the speedy response. Can you email me privately so I can reply with the epub attachment. My address is steveridout@gmail.com
